force-app/main/default/objects/Ancestry__c/Ancestry__c.object-meta.xml
<CustomObject>
    <label>Ancestry</label>
    <nameField>
        <displayFormat>FT# {0000000}</displayFormat>
        <label>Ancestry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ancestries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ancestry__c/fields/Ancestry__c.field-meta.xml
<CustomField>
    <fullName>Ancestry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Ancestry__c</referenceTo>
    <relationshipLabel>Ancestries (Partner)</relationshipLabel>
    <relationshipName>Ancestries1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ancestry__c/fields/Family_Name__c.field-meta.xml
<CustomField>
    <fullName>Family_Name__c</fullName>
    <label>Family Name</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ancestry__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ancestry__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mother</label>
    <referenceTo>Ancestry__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/**
 * @description       :
 * @author            : merv@merv.org.uk
 * @group             :
 * @last modified on  : 14-12-2020
 * @last modified by  : merv@merv.org.uk
 * Modifications Log
 * Ver   Date         Author             Modification
 * 1.0   14-12-2020   merv@merv.org.uk   Initial Version
 **/
@isTest
public with sharing class TestDataFactory {
	public static void theSimpsons() {
		Ancestry__c abe = new Ancestry__c(
			Family_Name__c = 'Simpson',
			First_Name__c = 'Abraham Jebediah "Abe"'
		);
		insert abe;

		Ancestry__c mona = new Ancestry__c(
			Family_Name__c = 'Simpson',
			First_Name__c = 'Mona Penelope',
			Ancestry__c = abe.Id
		);
		insert mona;

		abe.Ancestry__c = mona.Id;
		update abe;

		Ancestry__c clarence = new Ancestry__c(
			Family_Name__c = 'Bouvier',
			First_Name__c = 'Clarence "Clancy"'
		);
		insert clarence;

		Ancestry__c jacqueline = new Ancestry__c(
			Family_Name__c = 'Bouvier',
			First_Name__c = 'Jacqueline Ingrid',
			Ancestry__c = clarence.Id
		);
		insert jacqueline;

		clarence.Ancestry__c = jacqueline.Id;
		update clarence;

		Ancestry__c homer = new Ancestry__c(
			Family_Name__c = 'Simpson',
			First_Name__c = 'Homer Jay',
			Parent__c = mona.Id
		);
		insert homer;

		Ancestry__c marjorie = new Ancestry__c(
			Family_Name__c = 'Simpson',
			First_Name__c = 'Marjorie Jacqueline Bouvier',
			Ancestry__c = homer.Id,
			Parent__c = jacqueline.Id
		);
		insert marjorie;

		homer.Ancestry__c = marjorie.Id;
		update homer;

		Ancestry__c selma = new Ancestry__c(
			Family_Name__c = 'Bouvier',
			First_Name__c = 'Selma',
			Parent__c = jacqueline.Id
		);
		insert selma;

		Ancestry__c patty = new Ancestry__c(
			Family_Name__c = 'Bouvier',
			First_Name__c = 'Patty',
			Parent__c = jacqueline.Id
		);
		insert patty;

		Ancestry__c bartholomew = new Ancestry__c(
			Family_Name__c = 'Simpson',
			First_Name__c = 'Bartholomew JoJo',
			Parent__c = marjorie.Id
		);
		insert bartholomew;

		jacqueline.Parent__c = bartholomew.Id;
		update jacqueline;

		Ancestry__c lisa = new Ancestry__c(
			Family_Name__c = 'Simpson',
			First_Name__c = 'Lisa Marie',
			Parent__c = marjorie.Id
		);
		insert lisa;

		Ancestry__c margaret = new Ancestry__c(
			Family_Name__c = 'Simpson',
			First_Name__c = 'Margaret Evelyn',
			Parent__c = marjorie.Id
		);
		insert margaret;
	}
}