force-app/main/default/objects/Ancestry__c/Ancestry__c.object-meta.xml
<CustomObject>
    <label>Ancestry</label>
    <nameField>
        <displayFormat>FT# {0000000}</displayFormat>
        <label>Ancestry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ancestries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ancestry__c/fields/Ancestry__c.field-meta.xml
<CustomField>
    <fullName>Ancestry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Ancestry__c</referenceTo>
    <relationshipLabel>Ancestries (Partner)</relationshipLabel>
    <relationshipName>Ancestries1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ancestry__c/fields/Family_Name__c.field-meta.xml
<CustomField>
    <fullName>Family_Name__c</fullName>
    <label>Family Name</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ancestry__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ancestry__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mother</label>
    <referenceTo>Ancestry__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AncestryHelperTest.cls
/**
 * @description       :
 * @author            : merv@merv.org.uk
 * @group             :
 * @last modified on  : 14-12-2020
 * @last modified by  : merv@merv.org.uk
 * Modifications Log
 * Ver   Date         Author             Modification
 * 1.0   14-12-2020   merv@merv.org.uk   Initial Version
 **/
@isTest
public with sharing class AncestryHelperTest {
	@isTest
	public static void testGetAncestors() {
		Ancestry__c bart = [
			SELECT Id, Name, First_Name__c, Family_Name__c, Parent__c
			FROM Ancestry__c
			WHERE First_Name__c = 'Bartholomew JoJo'
		];

		Test.startTest();

		List<Id> ancestors = AncestryHelper.getAncestors(bart.Id);

		Test.stopTest();
	}

	@TestSetup
	static void makeData() {
		TestDataFactory.theSimpsons();
	}
}